name: behavior_tree
description: A behavior tree implementation written in dart. This package is designed to be used for implementing AI in games.
version: 1.0.0
repository: https://github.com/flame-engine/flame/tree/main/packages/flame_behavior_tree/behavior_tree

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.9.1

dev_dependencies:
  flame_lint: ^1.1.2
  lints: ^3.0.0
  mocktail: ^1.0.1
  test: any
